server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/inventorydb

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/inventorydb
